### ISSUE TITLE
Preview broken in TYPO3 9.5

### ISSUE THREAD

**Issue by nito-web** [Yoast/Yoast-SEO-for-TYPO3#224] opened 2018-10-27 14:52 UTC
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
I installed your Extension in a TYPO3 9.5 and filled data in title, description, og-... and twitter-... and its working perfect in the frontend.

But in the backend, the preview is allays showing `This is an example title - edit by clicking here  
Slug preview:example.com/example-post/
Meta description preview:Please provide a meta description by editing the snippet below.`

The Browser fires a GET Request to `Request URL: http://domain.test/services?type=1480321830&uriToCheck=%252Fservices&cHash=2b9c4351cf6d145e369fe46f5f17c8b3` and gets a `Status Code: 200 OK` back, but in the Response Body is always a `{"error":"Kon niet lezen"}`

### Logs
`PHP message: PHP Warning:  get_meta_tags(/services): failed to open stream: No such file or directory in /.../typo3conf/ext/yoast_seo/Classes/UserFunctions/SnippetPreview.php on line 16
', referer: http://domain.test/typo3/index.php?route=%2Fweb%2Flayout%2F&token=885a9011f2a5dbe3a85fbada2c93062b607217c2&id=4`

### Technical info
* TYPO3 version: 8.5.0
* Yoast SEO version: 4.0.0

**Comment by haassie** [comment] 2018-10-28 13:48
Please check if #225 will fix this issue

**Comment by nito-web** [comment] 2018-10-29 05:16
The error changed, now I get an error message instead of the preview:

`We got an error 500 (Internal Server Error) when requesting /?type=1480321830&uriToCheck=%252F&cHash=fe186204612be6a51c8dd8722eae464e to analyse your content. Please check your javascript console for more information.`

## Logfiles
[Mon Oct 29 12:11:14.306799 2018] [proxy_fcgi:error] [pid 300:tid 123145400655872] [client 127.0.0.1:51136] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TYPO3\\CMS\\Core\\Exception: <url> malformed in /.../Sites/domain.test/Server/htdocs/typo3conf/ext/yoast_seo/Classes/UserFunctions/SnippetPreview.php:84

Stack trace:

#0 /.../Sites/domain.test/Server/htdocs/typo3conf/ext/yoast_seo/Classes/UserFunctions/SnippetPreview.php(16): YoastSeoForTypo3\\YoastSeo\\UserFunctions\\SnippetPreview->getContentFromUrl('/services')

#1 [internal function]: YoastSeoForTypo3\\YoastSeo\\UserFunctions\\SnippetPreview->render('', Array)

#2 /.../Sites/typo3/typo3_src-9.5.0/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(5942): call_user_func_array(Array, Array)

#3 /.../Sites/typo3/typo3_src-9.5.0/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php(41): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('YoastSeoForTypo...', Array, '')

#4 /.../Sites/typo3/typo3_src-9.5.0/typo3/sysext/frontend/Classes...\n', referer: http://domain.test/typo3/index.php?route=%2Fweb%2Flayout%2F&token=697db40fd586a95afda5d59096a2c2e1ed91a710&id=4

**Comment by Zillion01** [comment] 2018-11-21 16:16
Yup, TYPO3 9.5.  `We got an error 500 (Internal Server Error) when requesting https://bliep.test/?type=1480321830&uriToCheck=https%253A%252F%252Fbliep.test%252F&cHash=7d7487fe50e47178e2ff1906986a5712 to analyse your content. Please check your javascript console for more information.`

**Comment by prathers** [comment] 2019-01-16 15:59
I can't reproduce after updating to v4.1.0 master

**Comment by haassie** [comment] 2019-01-16 19:03
In that case, I will close the issue. Sorry again for the late response.

**Closed by haassie** 2019-01-16 19:03 UTC
Labels: needs-code-review, needs-testing

**Comment by boettner-it** [comment] 2019-01-18 07:41
I got a similar error when running TYPO3 9.5.3 and yoast_seo 4.1.0.

Reason or the broken preview on my side was an nginx IP address restriction:
```
allow 123.124.125.126;    
deny all;
```
With adding the servers own IP and setting `['FE']['pageNotFoundOnCHashError'] = false` the preview was back.

Will apply to Apache .htaccess in a similar manner:
```
Order deny,allow
Deny from all
Allow from 123.124.125.126
Satisfy Any
```

**Comment by rickymathew** [comment] 2019-02-27 10:45
I still got the error in version 4.1.0 as follows 
We got an error 0 (error) when requesting https://test.com/en/?type=1480321830&uriToCheck=https%253A%252F%252Ftest.com%252Fen%252Fproducts-solutions&cHash=de30cf79b51c6289cd338f44b7110644 to analyse your content. Please check your javascript console for more information.

Any one have any workaround?

**Comment by Tiimiiiboy** [comment] 2019-08-21 06:42
Hello everybody,
I have installed the Yoast Extension on my Typo3 installation. Unfortunately I do not see the preview in the backend.

In the developer console of Chrome I get the error message:



### Error Log
`plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51 TypeError: Cannot read property 'replace' of undefined
    at e.default (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:34)
    at e.value (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:68)
    at e.value (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:68)
    at qr (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51)
    at Ar (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51)
    at Rr (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51)
    at Yo (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51)
    at Go (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51)
    at Cs (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51)
    at As (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51)`

### Technical info
* TYPO3 version: 9.5.8
* Yoast SEO version: 5.0.1
* Relevant extensions in case of a bug:
