### ISSUE TITLE
Error trying to save alternative page-title on a News Item

### ISSUE THREAD

**Issue by Alexander-Hagemeier** [Yoast/Yoast-SEO-for-TYPO3#187] opened 2018-06-04 12:12 UTC
Hello,

I am running a Typo3 in 8.7.10 and using the Yoast Seo Extension (2.1.0) and News System Extension (6.3.0).

If I try so save an alternative page-title for a News, I get this error:

`	
1: These fields of record {recordID} in table "tx_news_domain_model_news" have not been saved correctly: l10n_diffsource! The values might have changed due to type casting of the database`

Despite this error message, the alternative page title seems to be saved. But I wonder how this error can occur.

Does anyone have faced the same or a similar problem?

Thanks a lot in anticipation.

**Comment by haassie** [comment] 2018-06-13 21:08
Hi Alexander,

Thanks for your report. Is it possible for you to try disabling the Yoast extension and try it again? Based on your error, I wonder if this is issue caused by the Yoast extension.

Can you verify if this issue resolves when you disable the Yoast extension?

**Comment by Alexander-Hagemeier** [comment] 2018-06-26 13:45
Hi haasie,

I disabled the extension and tried it againt. The same error occurs :(

**Comment by haassie** [comment] 2018-07-10 18:54
So in that case, I will close this issue because it is not related to the Yoast plugin.

**Closed by haassie** 2018-07-10 18:54 UTC
Labels: needs-feedback
