### ISSUE TITLE
news TCA settings brakes element rendering

### ISSUE THREAD

**Issue by hacksch** [Yoast/Yoast-SEO-for-TYPO3#160] opened 2018-02-28 11:18 UTC
PHP 7.0
TYPO3 7.6.24
Extension v2.0.2

When i have an element inserted as a reference it will not rendered anymore. The log says:

>  Oops, an error occurred! Code: 20180228092457cad7c52a - {"exception":"InvalidArgumentException: There is no entry in the $TCA array for the table \"tx_news_domain_model_news\". This means that the function enableFields() is called with an invalid table name as argument.

A solution could be to check for installed news extension in the beginning of /Classes/Utility/YoastUtility.php

```
if (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('news') === false) {
    return;
}
```

**Comment by haassie** [comment] 2018-02-28 11:28
hi @hacksch, thanks for your reports. You get this error in frontend? Will check today!

**Comment by hacksch** [comment] 2018-02-28 11:34
In frontend i get only a output of "Oops, an error occurred! Code: 20180228092457cad7c52a". Found the real exception in typo3 log. 

Backtrace is:

> request="062cfc91c7443" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 20180228092457cad7c52a - {"exception":"InvalidArgumentException: There is no entry in the $TCA array for the table \"tx_news_domain_model_news\". This means that the function enableFields() is called with an invalid table name as argument. in \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/Page\/PageRepository.php:1213\nStack trace:\n#0 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(7985): TYPO3\\CMS\\Frontend\\Page\\PageRepository->enableFields('tx_news_domain_...', false, Array)\n#1 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/RecordsContentObject.php(156): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->enableFields('tx_news_domain_...')\n#2 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/RecordsContentObject.php(77): TYPO3\\CMS\\Frontend\\ContentObject\\RecordsContentObject->collectRecordsFromSource('tt_content_5369', Array)\n#3 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\RecordsContentObject->render(Array)\n#4 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\RecordsContentObject), Array)\n#5 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/FluidTemplateContentObject.php(263): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('RECORDS', Array)\n#6 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/FluidTemplateContentObject.php(97): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->getContentObjectVariables(Array)\n#7 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render(Array)\n#8 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject), Array)\n#9 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(841): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, 'lib.fluidConten...')\n#10 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/CaseContentObject.php(44): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, 'shortcut')\n#11 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject->render(Array)\n#12 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject), Array)\n#13 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(841): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CASE', Array, 'tt_content')\n#14 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentContentObject.php(97): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CASE', Array, '')\n#15 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\ContentContentObject->render(Array)\n#16 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\ContentContentObject), Array)\n#17 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/ViewHelpers\/CObjectViewHelper.php(119): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CONTENT', Array)\n#18 [internal function]: TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper->render('content', NULL, NULL, '')\n#19 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/ViewHelper\/AbstractViewHelper.php(268): call_user_func_array(Array, Array)\n#20 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/ViewHelper\/AbstractViewHelper.php(249): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#21 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/SyntaxTree\/ViewHelperNode.php(137): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#22 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/SyntaxTree\/AbstractNode.php(48): TYPO3\\CMS\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode->evaluate(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#23 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/ViewHelper\/AbstractViewHelper.php(312): TYPO3\\CMS\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode->evaluateChildNodes(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#24 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/ViewHelpers\/SectionViewHelper.php(100): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->renderChildren()\n#25 [internal function]: TYPO3\\CMS\\Fluid\\ViewHelpers\\SectionViewHelper->render()\n#26 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/ViewHelper\/AbstractViewHelper.php(268): call_user_func_array(Array, Array)\n#27 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/ViewHelper\/AbstractViewHelper.php(249): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#28 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/SyntaxTree\/ViewHelperNode.php(137): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#29 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/View\/AbstractTemplateView.php(247): TYPO3\\CMS\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode->evaluate(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#30 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/ViewHelpers\/RenderViewHelper.php(121): TYPO3\\CMS\\Fluid\\View\\AbstractTemplateView->renderSection('Content', Array, false)\n#31 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/ViewHelpers\/RenderViewHelper.php(98): TYPO3\\CMS\\Fluid\\ViewHelpers\\RenderViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#32 [internal function]: TYPO3\\CMS\\Fluid\\ViewHelpers\\RenderViewHelper->render('Content', NULL, Array, false)\n#33 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/ViewHelper\/AbstractViewHelper.php(268): call_user_func_array(Array, Array)\n#34 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/ViewHelper\/AbstractViewHelper.php(249): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#35 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/SyntaxTree\/ViewHelperNode.php(137): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#36 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/SyntaxTree\/AbstractNode.php(48): TYPO3\\CMS\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode->evaluate(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#37 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/SyntaxTree\/RootNode.php(27): TYPO3\\CMS\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode->evaluateChildNodes(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#38 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/ParsingState.php(85): TYPO3\\CMS\\Fluid\\Core\\Parser\\SyntaxTree\\RootNode->evaluate(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#39 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/fluid\/Classes\/View\/AbstractTemplateView.php(189): TYPO3\\CMS\\Fluid\\Core\\Parser\\ParsingState->render(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#40 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/FluidTemplateContentObject.php(300): TYPO3\\CMS\\Fluid\\View\\AbstractTemplateView->render()\n#41 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/FluidTemplateContentObject.php(102): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->renderFluidView()\n#42 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render(Array)\n#43 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject), Array)\n#44 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(805): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, '10')\n#45 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/Page\/PageGenerator.php(210): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet(Array)\n#46 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/Http\/RequestHandler.php(216): TYPO3\\CMS\\Frontend\\Page\\PageGenerator::renderContent()\n#47 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/core\/Classes\/Core\/Bootstrap.php(307): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#48 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/typo3\/sysext\/frontend\/Classes\/Http\/Application.php(78): TYPO3\\CMS\\Core\\Core\\Bootstrap->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#49 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/index.php(33): TYPO3\\CMS\\Frontend\\Http\\Application->run()\n#50 \/var\/www\/aoe7lts\/devbox\/htdocs\/typo3_src\/index.php(34): {closure}()\n#51 {main}"}

**Comment by haassie** [comment] 2018-02-28 11:41
Thanks. Will check if I can reproduce it. Will work on this tonight.

**Comment by haassie** [comment] 2018-02-28 20:33
To what kind of element is the reference pointing? Your proposed solution to check on EXT:news in YoastUtility isn't the right solution because you need those functions also when you don't have EXT:news installed. I think you mean in Configuration/TCA/Overrides/tx_news_domain_model_news.php?

**Comment by haassie** [comment] 2018-02-28 20:34
I can't reproduce it at the moment so if you can give me some more information about your setup, that would be great!

**Comment by hacksch** [comment] 2018-03-01 06:34
Hello,

yes my current solution is to check in Configuration/TCA/Overrides/tx_news_domain_model_news.php.

I can only add that the referenced element is an gridelement with fields only. so no container fields are inside. I got the error on different pages with different elements but everytime in the constellation gridelement referenced from another page.
Normal element or gridelements on the same page are not affected.

Maybe i will find sometime during the day to check with line(s) of TCA configuration are the trigger

**Comment by haassie** [comment] 2018-03-01 19:24
Can you send me a screenshot of your page module (or even a small database dump)? I can't reproduce the issue.

**Comment by hacksch** [comment] 2018-03-09 08:59
Hello,
i found out that the lines 76-80 in the tx_news_domain_model_news.php file are responsible for the bug.
Somehow with these lines the table tx_news_domain_model_news will checked by PageRepository->enableFields()

And i noticed only with these lines the TCA configuration will extended. Without them there are no entries.
![image](https://user-images.githubusercontent.com/5759188/37198950-4a75f896-2380-11e8-828d-582d9a3619a3.png)


In our system we are using fluid templates and grid elements. Here a screenshot of the element:

Backend view of the element. It's a custom gridelement referenced from another page
![image](https://user-images.githubusercontent.com/5759188/37198396-7b05b1ce-237e-11e8-8643-9652f585ce8e.png)


Why the extension needs the TCA configuration for that table when news isn't installed?

**Comment by saitho** [comment] 2018-03-14 08:25
This also applies to the TCA overrides for extension tx_cal_event.

**Comment by twllndr** [comment] 2018-03-20 12:30
Had the same problem in an 7.6.25 installation. I referenced normal content elements but got the same error. Fixed it with the php code in the first comment. Would be good, if this code (and the database fields too) wouldn't be included at all, when news or cal isn't installed.

**Comment by dr-bock** [comment] 2018-03-21 10:28
Same error here. We must remove the TCA-Overrides for tx_news and tx_cal_event get our installation to work.

It would be nice if the TCA overrides would not be loaded and the database tables/fields would not be created if the extensions were not installed.

**Comment by cedev-de** [comment] 2018-04-03 07:02
I use this in ext_tables.php of my sitepackage Extension. Maybe this helps somebody.

`
    if(!\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('news')){
        unset($GLOBALS['TCA']['tx_news_domain_model_news']);
    }
    if(!\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('cal')){
        unset($GLOBALS['TCA']['tx_cal_event']);
    }
`

**Comment by Pavitro** [comment] 2018-06-12 13:24
Even without the use of News or Cal an element inserted as a reference will not be rendered anymore.

**Comment by haassie** [comment] 2018-07-21 06:05
We removed the EXT:News and EXT:cal tables and configuration and will release a new major version. Will be released next week.

**Closed by haassie** 2018-07-21 06:05 UTC
Labels: bug
