### ISSUE TITLE
Javascript error in backend

### ISSUE THREAD

**Issue by RonaldKools** [Yoast/Yoast-SEO-for-TYPO3#267] opened 2019-05-16 18:54 UTC
* [X ] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [ X] I've searched for any related issues and avoided creating a duplicate issue.

I am new to the Yoast plugin and installed the latest version "as is" to see if we'd like to integrate it into our sites. The documentation says it is preconfigured for "pages", so no configuration, just a plain install. In the backend I tried opening a page and the Readability analysis and Focus keywords keep loading forever (ball-animation) and the Snippet preview is empty.

In the console of Chrome it shows 2 errors (see below). Firefox gives similar errors.

### How can we reproduce this behavior?
1. Install the latest version of the Yoast plugin in Typo3 8.7.25
2. Open the developers console in Chrome.
2. Edit the page properties of a single page and click the Yoast tab.

I checked the ajax call and it is showing content of the page itself, so I think that is good:
?type=1480321830&pageIdToCheck=1&languageIdToCheck=0&additionalGetVars=

### Logs

CHROME:
plugin.js?bust=bb1bda1939f429511b7bc62fc2d78bd5fd6c6b0c:51 TypeError: Cannot read property 'replace' of undefinedat e.default (VM145 plugin.js:formatted:31590)at e.value (VM145 plugin.js:formatted:68767)at e.value (VM145 plugin.js:formatted:68864)at qr (VM145 plugin.js:formatted:58889)at Ar (VM145 plugin.js:formatted:58879)at Rr (VM145 plugin.js:formatted:59098)at Yo (VM145 plugin.js:formatted:60626)at Go (VM145 plugin.js:formatted:60650)at Cs (VM145 plugin.js:formatted:61052)at As (VM145 
plugin.js:formatted:61006)

plugin.js?bust=bb1bda1939f429511b7bc62fc2d78bd5fd6c6b0c:34 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefinedat e.default (VM145 plugin.js:formatted:31590)at e.value (VM145 plugin.js:formatted:68767)at e.value (VM145 plugin.js:formatted:68864)at qr (VM145 plugin.js:formatted:58889)at Ar (VM145 plugin.js:formatted:58879)at Rr (VM145 plugin.js:formatted:59098)at Yo (VM145 plugin.js:formatted:60626)at Go (VM145 plugin.js:formatted:60650)at Cs (VM145 plugin.js:formatted:61052)at As (VM145 plugin.js:formatted:61006)

FIREFOX:
TypeError: "a is undefined"

### Technical info
* TYPO3 version: Typo3 8.7.25
* Yoast SEO version: 5.0.1 (composer installation)
* Relevant extensions in case of a bug: -

**Comment by hkremer** [comment] 2019-05-17 13:30
I have exact the same error. I have installed Yoast on 6 sites without any problems. But one that is almost the same as the others, i got this javascript error too.

**Comment by hkremer** [comment] 2019-05-20 08:54
I found the reason. If the host cannot resolve itself, you get this javascript error.
The javascript should not give this error, but I could workaround it by adding the host itself in the /etc/hosts on the server.

**Comment by RonaldKools** [comment] 2019-05-20 12:14
Actually, in our case this was already working correctly. 

But I solved it too: yoast_seo_preview.config.debug = 0 is missing in the setup, causing Typo3 to inject a Parsetime comment in the JSON and thus rendering invalid JSON.

Maybe yoast_seo_preview.config.debug = 0 can be added by default?

**Comment by haassie** [comment] 2019-05-20 12:44
Hi you are both right. I will let this issue open and we will fix it in the next version. Adding the debug = 0 and giving you a proper error message when the server can not access it's own domain.

**Comment by RonaldKools** [comment] 2019-05-21 16:12
Perfect, thanx!

**Comment by KaiBroenstrup** [comment] 2019-06-02 09:11
Hey, where do i have to put the "yoast_seo_preview.config.debug = 0" just in setup typoscript? Thats not working here...

**Comment by RonaldKools** [comment] 2019-06-04 15:40
@KaiBroenstrup yes, I just added yoast_seo_preview.config.debug = 0 to the setup.

**Comment by typecat** [comment] 2020-01-27 14:16
I have the same error output after an Upgrade form Yoast SEO 3.0.5 to 5.1.1 using

-  TYPO3 8.7.24
- RealURL 2.5.0

But the cause of the error is in my case not the debug setting, but the editor. If I'm logged in as administrator, the scoring works fine, but if I'm logged in as editor, I see the error described above.
The editor has rights to  all Yoast relevant page fields and the Dashboard and Overview modules.
Also the JSON response for the AJAX call looks the same in both cases.

Did I maybe miss some necessary permission configuration? The [documentation](https://docs.typo3.org/p/yoast-seo-for-typo3/yoast_seo/master/en-us/Configuration/Permissions/Index.html) on this one is not very detailed.

**Comment by RinyVT** [comment] 2020-12-13 16:28
@typecat Is this issue still present in the latest version?
I think your issue may be different from the original problem of this issue, is it also the `replace` error?
We have changed some javascript in the latest versions to prevent this error so I'm curious if you're still having problems (or that the error message is more clear now).

**Comment by typecat** [comment] 2020-12-14 09:17
Hello @haassie,
I haven't tried a newer version, because we removed the yoast extension during the TYPO3 upgrade. Unfortunately it caused too many problems on TYPO3 8.7 (including this one), so the client decided that the benefit of the extension is not worth the troubles.

**Comment by RinyVT** [comment] 2020-12-14 09:41
Sorry to hear that! We'll try to support v8 as long as we can, but the extension is currently more stable for v9 and v10 because of core-improvements for SEO, Routing and AJAX backend vs frontend. 
I will close this issue for now, but feel free to open a new issue if this issue occurs again.

**Closed by RinyVT** 2020-12-14 09:41 UTC
Labels: needs-feedback
