### ISSUE TITLE
Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Site\Entity\SiteLanguage::getWebsiteTitle()

### ISSUE THREAD

**Issue by bibusdax** [Yoast/Yoast-SEO-for-TYPO3#394] opened 2020-11-18 09:33 UTC
* [X] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
This error came with the update to yoast_seo 7.0.5 in combination with yoast_seo_premium 4.1.0
As soon as someone works on a page, we get an Error in the log like the following one:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Site\Entity\SiteLanguage::getWebsiteTitle() | Error thrown in file /var/www/clients/client1/web1/web/typo3conf/ext/yoast_seo/Classes/Frontend/AdditionalPreviewData.php in line 59. Requested URL: https://www.bibus.es/en/contact/contact-form/
This is since the update from 7.0.3 to 7.0.5

### Please describe what you expected to happen and why.
I expect no such error to happen

### How can we reproduce this behavior?
I can work on a page, e.g. on a web form and then I get the entry in the log.
If necessary, I can give access to our system to Richard Haeser as I did in previous cases.

### Logs
If applicable, add logs to help explain your problem.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Site\Entity\SiteLanguage::getWebsiteTitle() | Error thrown in file /var/www/clients/client1/web1/web/typo3conf/ext/yoast_seo/Classes/Frontend/AdditionalPreviewData.php in line 59. Requested URL: https://www.bibus.es/en/contact/contact-form/

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Site\Entity\SiteLanguage::getWebsiteTitle() | Error thrown in file /var/www/clients/client1/web1/web/typo3conf/ext/yoast_seo/Classes/Frontend/AdditionalPreviewData.php in line 59. Requested URL: https://www.bibus.es/en/contact/contact-form/

### Technical info
* TYPO3 version: 9.5.23 patched
* Yoast SEO version: 7.0.5
* Relevant extensions in case of a bug: yoast_seo, yoast_seo_premium, forms

**Comment by haassie** [comment] 2020-11-18 09:37
This is a duplicate of https://github.com/Yoast/Yoast-SEO-for-TYPO3/issues/392. Will be released today.

**Closed by haassie** 2020-11-18 09:37 UTC

**Comment by bibusdax** [comment] 2020-11-18 09:46
Dear Richard,
thank you very much. I did not look in the closed issues.
Sorry for the inconvenience.

Stay healthy and best regards,

Patrick

P.S. hopefully there will be some TYPO3 event again in the future where we can have a beer.

**Comment by haassie** [comment] 2020-11-18 09:47
No problem. Stay safe as well and hopefully we can soon meet again at an event indeed!
