### ISSUE TITLE
preview and bars for editors in TYPO3 v11 not working correctly

### ISSUE THREAD

**Issue by paul-keller** [Yoast/Yoast-SEO-for-TYPO3#506] opened 2022-06-09 09:32 UTC
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
In the seo tab of the page properties for editors the preview and the bars for title and description do not load the most of the time.
It seems to have a javascript error in plugin.js
This happens with version 8.1.0 in TYPO3 11. In TYPO3 10 it works fine.

### Please describe what you expected to happen and why.
Preview and bars should be displayed, as in TYPO3 10.

### How can we reproduce this behavior?
1. Switch to non admin user
2. Open page properties an switch to seo tab
3. Preview keeps loading, nothing is displayed

### Screenshots
<img width="413" alt="image" src="https://user-images.githubusercontent.com/6952891/172815039-22d703ad-54ef-47ba-8f6a-902daf5f3d8d.png">

### Logs
If applicable, add logs to help explain your problem.

### Technical info
* TYPO3 version: 11.5.10
* Yoast SEO version: 8.1.0
* Relevant extensions in case of a bug:

**Comment by paul-keller** [comment] 2022-06-09 09:45
Interesting fact: It does not happen every time. Inbetween works perfectly and the editor sees the preview and the bars correctly. But then we allways get that javascript error again.

**Comment by RinyVT** [comment] 2022-06-15 14:48
@paul-keller Are you able to test the pull request I have opened for fixes for CMS11?
https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/505

This should fix the javascript error and the progress bar for title not showing up.
These fixes are not ideal and will be more structurally fixed in the future, but for now this should prevent the errors.

**Comment by RinyVT** [comment] 2022-06-22 15:48
Due to the upcoming release, I have merged the pull request #505.
I'll close this issue for now, if the problem is still present after the next release please feel free to open a new issue.

**Closed by RinyVT** 2022-06-22 15:48 UTC
