### ISSUE TITLE
harmful canonical configuration

### ISSUE THREAD

**Issue by Nemo64** [Yoast/Yoast-SEO-for-TYPO3#186] opened 2018-05-16 08:54 UTC
The default configuration for `currentURL` and `canonicalURL` is harmful.
It uses `addQueryString` **AND** `useCacheHash`.

That means if i request my page with the url `http://example.com/?foobar=barfoo`. Then suddenly, the canonical start page url is `http://example.com/?foobar=barfoo&cHash=3104304620714d71c12787dd12636612`.

Moreover, that result will get cached in the none-cHash version (if the cache was cold). So as long as the cache is active (24 hours), that url is now my new start page according to the canonical.

It even gets worse than that. The cHash is meant to prevent cache spam. But since the canonical now takes any url and generates a cHash for you, if i wanted to attack a page, i just create new urls and after that just call the canonical url to get a new cache entry. _Lets see how many millions of cache entries the database can take._

It is sort-of documented in the typoscript docu as well: https://docs.typo3.org/typo3cms/TyposcriptReference/Functions/Typolink/Index.html#addquerystring

So there are 2 solutions i know of.

- Most sites generate the canonical manually, i understand that thats hard since you want your extension to be a drop-in-extension. And also that is kind of annoying.
- The second is a little more complicated, it involves creating a parameter list from the `TypoScriptFrontendController` and the `cHash_array`. That array contains all parameters that are considered for for the current cache of the page **but also the encryption key** which you'd have to remove first.

**Comment by haassie** [comment] 2018-05-16 08:57
Thanks for your report. Will check it today!

**Comment by haassie** [comment] 2018-05-16 09:34
Yes please, if you have any possible solutions, please send them. If you want to create a pull request you are also more than welcome!

**Comment by Nemo64** [comment] 2018-05-16 09:58
I have something else to do right now, but i may look into it later.

Basically my solution contained writing my own `getData` method.
That allows me to use `typolink.additionalParameters.data = canonical_parameters`.
The hook for that looks like this.
```php
class CanonicalParametersGetDataHook implements ContentObjectGetDataHookInterface
{
    /**
     * Extends the getData()-Method of \TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer to process more/other commands
     *
     * @param string $getDataString Full content of getData-request e.g. "TSFE:id // field:title // field:uid
     * @param array $fields Current field-array
     * @param string $sectionValue Currently examined section value of the getData request e.g. "field:title
     * @param string $returnValue Current returnValue that was processed so far by getData
     * @param \TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer $parentObject Parent content object
     * @return string Get data result
     */
    public function getDataExtension($getDataString, array $fields, $sectionValue, $returnValue, ContentObjectRenderer &$parentObject)
    {
        if ($getDataString !== 'canonical_parameters') {
            return $returnValue;
        }

        /** @var TypoScriptFrontendController $tsfe */
        $tsfe = $GLOBALS['TSFE'];
        $cHash_array = $tsfe->cHash_array;
        unset($cHash_array['encryptionKey']);
        return GeneralUtility::implodeArrayForUrl('', $cHash_array);
    }
}
```

**Comment by olivermeckel** [comment] 2018-10-29 13:46
Any solutions out-of-the-box?

I have the same issue
I want to set canonical urls to avoid duplicate content for the search and contact page caused by dynamic getParameters

For example the canonical url for contact page is configured to
https://www.hps.de/kontakt/

Dynamic getparameter ar written also to canonical url
https://www.hps.de/kontakt/?tx_powermail_pi1%5Bartikelnummer%5D=Drehhocker%20207%20PU&cHash=29c322e14770f104b21552e0220f0d0b
instead of routing to the main url
https://www.hps.de/kontakt/

Are there any solutions?
i use typo3 8.7 with yoast_seo 3.0.4

**Comment by lisardo2** [comment] 2020-06-08 17:31
Any solution here? I do have many discusssions with clients about wrong canonicals which get persisted via the cache. Every time when a page is called with any parameter and the page is not cached yet, the call results in a now cached page with wrong canonical.

**Comment by RinyVT** [comment] 2021-10-05 14:13
I'm going to close this issue, since the canonical url is being handled by TYPO3 core (`EXT:seo`) nowadays.

**Closed by RinyVT** 2021-10-05 14:13 UTC
Labels: bug
