### ISSUE TITLE
Add FAL for Facebook and Twitter image

### ISSUE THREAD

**Issue by mdbloch** [Yoast/Yoast-SEO-for-TYPO3#76] opened 2017-07-20 14:53 UTC
I really think, the Facebook and Twitter image should be a FAL reference.

**Comment by haassie** [comment] 2017-07-20 18:16
It is based on FAL references. Only in the backend module it is not the look and feel you know from normal. If you take a look at the page properties, you can see it is a FAL reference.

Or do you think otherwise?

**Comment by mdbloch** [comment] 2017-07-21 09:39
You are right, but i think it would be better if you could choose from existing files, because customer sometimes have their custom structure where they want to put their images. So selecting it from a folder or upload them to a folder would be more user friendly in my point of view.

**Comment by haassie** [comment] 2017-07-21 11:44
The problem is that we had to create an own backend module to do things the way we wanted it. The drawback is that we can't use functions that are default in TCA that easily. Until now I didn't find a solution to use the FAL dialog in an own backend module. If that is possible, I would definitely use that. Creating an "own" solution is not the right way in this case I think.

In CMS9 we want to integrate it even better in core so I hope in CMS9 this kind of issues will be gone.

**Comment by haassie** [comment] 2017-07-21 14:19
After a chat with Mathias I got some example code:
- https://bitbucket.typo3.com/projects/EXT/repos/pagetemplates/browse/Classes/Service/FormEngineService.php
- https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/FormEngine/Rendering/Index.html

**Comment by haassie** [comment] 2018-01-30 20:05
The way of setting images is now changed in v2 and merged into master

**Closed by haassie** 2018-01-30 20:05 UTC
Labels: enhancement
