### ISSUE TITLE
Make Readability and Focus keyword clickable

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/Yoast-SEO-for-TYPO3#52] opened 2017-04-19 15:29 UTC
<img width="909" alt="typo3_cms_demo__typo3_cms_7_6_13_" src="https://cloud.githubusercontent.com/assets/5147598/25188121/45339ae6-2525-11e7-9d6e-977a13f2f8ad.png">

* Clicking Readability should take the user to the Readability analysis.
<img width="903" alt="typo3_cms_demo__typo3_cms_7_6_13_" src="https://cloud.githubusercontent.com/assets/5147598/25188228/aa8ebbc8-2525-11e7-801d-85a91a46034b.png">

* Clicking Focus Keyword should take the user to the focus keyword field.
<img width="864" alt="typo3_cms_demo__typo3_cms_7_6_13_" src="https://cloud.githubusercontent.com/assets/5147598/25188259/bebfcc9a-2525-11e7-958c-764e3a535dd9.png">

**Comment by haassie** [comment] 2017-04-23 13:35
@tacoverdo Do you really want this? This isn't possible in the WP-plugin either and it will cause some serious (testing)work I'm afraid. The problem is that the tests will be done after the backend page is loaded. So easily do it with an anchor isn't possible. When doing it when the tests are done is causing problems because you don't want to scroll to the area's when changing for example the meta description.
So it is doable, but I'm questioning myself if it is word the amount of work.

**Comment by haassie** [comment] 2018-01-25 20:31
This is done a little bit different. When you click on the readability it will open a modalbox with the readability analysis. Clicking on the focus keyword, will open the focus keyword analysis. This will be included in version 2.

**Closed** 2018-01-25 20:32 UTC
Labels: enhancement
