### ISSUE TITLE
Customized title tag not rendered in TYPO3 8.7

### ISSUE THREAD

**Issue by akiessling** [Yoast/Yoast-SEO-for-TYPO3#274] opened 2019-06-13 19:44 UTC
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
The constants for titlePrepend and titleAppend do not seem to be used anymore, 
although the configuration is still present in TypoScript/Setup/CMS8.typoscript, only the regular title is printed out. 
Tested with v5 in TYPO3 8.7, but since i could not find any similar setting for TYPO3 9.5, this feature seems to be gone?

### Please describe what you expected to happen and why.
Since i did not find any deprecation/removal of that feature in https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/CHANGELOG.md, i'd expect this to still be working.

### How can we reproduce this behavior?
1. configure constant plugin.tx_yoastseo.titleAppend in TYPO3 8.7, check TS browser in lib.yoastSEO.pageTitleComplete and resulting title tag

### Technical info 
* TYPO3 version: 8.7
* Yoast SEO version: 5.0.1
* Relevant extensions in case of a bug:

**Comment by djangones** [comment] 2019-07-13 13:14
I can confirm that behaviour also for lib.yoastSEO.pageTilte and lib.yoastSEO.description which also seem to be ignored in the latest version. Maybe there ist another/new way to configure those elements but i was not able to find anything about this (breaking) change...

**Comment by Jashi** [comment] 2019-10-25 10:29
We can confirm this as well. The reason for this is that in TYPO3 8 Yoast now uses the PageTitle.php class to render the title which doesn't check or use append or prepend.

Our workaround right now is to disable the title via config.noPageTitle = 2 which removes the rendering done by yoast. Afterwards we build our own title via TS using the working TS from CMS8.typoscript


```
page.headerData {
    1 < lib.yoastSEO.pageTitleComplete
    1.wrap = <title>|</title>
...
...
}
```

**Comment by infabo** [comment] 2020-03-10 13:11
Seems like someone just dropped (intentionally or not) support for these options.

https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/v3.0.5/Classes/Frontend/PageRenderer/PageMetaRenderer.php

got replaced with something very, very, very basic:

https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Classes/Frontend/PageTitle.php

Very strange this happening. As this class is used for < 9.5 only. So why this implementation is not identical to the one from v3.0.5. We do not know.

```php
if (version_compare(TYPO3_branch, '9.5', '<')) {
    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_pagerenderer.php']['render-postProcess'][] =
        \YoastSeoForTypo3\YoastSeo\Canonical\CanonicalGenerator::class . '->generate';

    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_pagerenderer.php']['render-postProcess'][]
        = \YoastSeoForTypo3\YoastSeo\Frontend\PageTitle::class . '->render';
} else {
    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['usePageCache'][]
        = \YoastSeoForTypo3\YoastSeo\Frontend\UsePageCache::class;
}
```

**Comment by RinyVT** [comment] 2021-11-24 15:05
Due to the date of this issue and the removal of CMS8 support, I'll close this issue. Sorry if we did not fix this.

The generation of the page title is now handled with the standard frontend configuration:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Classes/Frontend/AdditionalPreviewData.php#L50-L133

It uses the website title from the site configuration, overridden by the `sitetitle` from the typoscript setup.
Then it checks the `pageTitleSeparator` to see what's needed for separation, `stdWrap` is applied here.
Afterwards it checks the `pageTitleFirst` configuration to see if the website-title should be prepended or appended.

Feel free to open a new issue if you encounter problems with the current version.

**Closed by RinyVT** 2021-11-24 15:05 UTC
